'use strict';
document.addEventListener('DOMContentLoaded',()=>{
const $=id=>document.getElementById(id);
const PALETTE=[['Ash Grey','#808079'],['Earth Brown','#806A5D'],['Corpus Grey','#808080'],['Hek Green','#7E806A'],['Kril Brown','#80745E'],['Gallium Grey','#78828C'],['Grustrag Grey','#807A6C'],['Saturn Brown','#806753'],['Sedna Grey','#807979'],['Derelict Black','#262626'],['Mars Red','#805F44'],['Infested Black','#363333'],['Void Black','#262020'],['Darvo Blue','#697280'],['Ordis Grey','#72727A'],['Mercury Brown','#807461'],['Anyo Grey','#363640'],['Ambulas Black','#342622'],['Shadow Grey','#80736B'],['Sargas Brown','#C58D4D'],['Jupiter Brown','#805A32'],['Phorid Red','#804330'],['Alad Blue','#5B6B80'],['Venus Brown','#4D4146']].map(([name,hex])=>({name,hex,rgb:h2r(hex),lab:null}));
PALETTE.forEach(c=>c.lab=toLab(c.rgb));
let sb=null,session=null,paletteFile=null,paletteMatches=[],activeSampler=0,sampleRadius=2;
let points=loadLayout()||[{x:.215,y:.395},{x:.215,y:.432},{x:.215,y:.469}],locked=[false,false,false];
const pCanvas=$('paletteCanvas'),pctx=pCanvas.getContext('2d',{willReadFrequently:true});
const fCanvas=$('furCanvas'),fctx=fCanvas.getContext('2d',{willReadFrequently:true});
let furImage=null,furActive=0,furSamples=[[],[],[]];

document.querySelectorAll('.modeTab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.modeTab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.modePanel').forEach(x=>x.classList.toggle('active',x.id===(b.dataset.mode==='palette'?'paletteMode':'furMode')))});

$('paletteFile').onchange=e=>loadPalette(e.target.files?.[0]);
function loadPalette(file){if(!file)return;paletteFile=file;$('paletteStatus').textContent='Opening screenshot…';const u=window.URL.createObjectURL(file),im=new Image();im.onload=()=>{pCanvas.width=im.naturalWidth;pCanvas.height=im.naturalHeight;pctx.drawImage(im,0,0);window.URL.revokeObjectURL(u);['paletteWorkspace','paletteResultsCard','detailsCard'].forEach(id=>$(id).hidden=false);$('paletteStatus').textContent=`Loaded ${file.name} · ${im.naturalWidth} × ${im.naturalHeight}`;place();updatePalette();runOcr();$('paletteWorkspace').scrollIntoView({behavior:'smooth'})};im.onerror=()=>$('paletteStatus').textContent='Could not open image.';im.src=u}

function place(){points.forEach((p,i)=>{const m=$('paletteMarker'+i);m.style.left=p.x*100+'%';m.style.top=p.y*100+'%';m.classList.toggle('locked',locked[i]);m.classList.toggle('focused',i===activeSampler)});document.querySelectorAll('.step').forEach((s,i)=>{s.classList.toggle('active',i===activeSampler);s.classList.toggle('locked',locked[i])});drawMagnifier()}
document.querySelectorAll('.step').forEach(s=>s.onclick=()=>{activeSampler=+s.dataset.focus;place()});
document.querySelectorAll('.marker').forEach(m=>{let drag=false;const move=e=>{if(!drag||locked[+m.dataset.i])return;e.preventDefault();const r=pCanvas.getBoundingClientRect(),i=+m.dataset.i;points[i]={x:clamp((e.clientX-r.left)/r.width),y:clamp((e.clientY-r.top)/r.height)};activeSampler=i;place();updatePalette()};m.onpointerdown=e=>{drag=true;m.setPointerCapture(e.pointerId);move(e)};m.onpointermove=move;m.onpointerup=m.onpointercancel=()=>drag=false});
$('lockSampler').onclick=()=>{locked[activeSampler]=!locked[activeSampler];$('lockSampler').textContent=locked[activeSampler]?'Unlock current sampler':'Lock current sampler';place()};
$('resetPaletteMarkers').onclick=()=>{points=[{x:.215,y:.395},{x:.215,y:.432},{x:.215,y:.469}];locked=[false,false,false];place();updatePalette()};
$('rememberLayout').onclick=()=>{localStorage.setItem('ljwillylPaletteLayout',JSON.stringify(points));$('rememberLayout').textContent='Layout remembered ✓'};
$('sampleSize').oninput=e=>{sampleRadius=+e.target.value;$('sampleSizeValue').textContent=sampleRadius;updatePalette();drawMagnifier()};
$('smallestSample').onclick=()=>{$('sampleSize').value=1;sampleRadius=1;$('sampleSizeValue').textContent='1';updatePalette();drawMagnifier()};

function updatePalette(){if(!pCanvas.width)return;paletteMatches=points.map(p=>rankPatch(pctx,pCanvas,p,sampleRadius));const names=['Primary / Base','Secondary','Tertiary'];$('paletteResults').innerHTML=paletteMatches.map((m,i)=>`<article class="result"><h3>${names[i]}</h3><div class="colourRow"><span class="swatch" style="background:${m.best.hex}"></span>${m.best.name}</div><div class="code">RGB(${m.rgb.join(', ')}) · ${m.best.hex}</div><div class="resultQuality ${m.mixed?'qualityBad':'qualityGood'}">${m.mixed?'Mixed pixels detected':'Flat sample'} · ΔE ${m.best.d.toFixed(1)}</div></article>`).join('');const bad=paletteMatches.some(m=>m.mixed||m.best.d>10);$('paletteWarning').hidden=!bad;if(bad)$('paletteWarning').textContent='One or more samplers contain mixed pixels or are far from an official palette colour. Reduce the sample size and move the crosshair further inside the box.';drawMagnifier()}

function drawMagnifier(){if(!pCanvas.width)return;const mag=$('magnifier'),mc=mag.getContext('2d'),p=points[activeSampler],size=Math.max(10,sampleRadius*4+10),sx=Math.max(0,p.x*pCanvas.width-size/2),sy=Math.max(0,p.y*pCanvas.height-size/2);mc.imageSmoothingEnabled=false;mc.clearRect(0,0,mag.width,mag.height);mc.drawImage(pCanvas,sx,sy,size,size,0,0,mag.width,mag.height);mc.strokeStyle='#fff';mc.lineWidth=2;mc.beginPath();mc.moveTo(mag.width/2,0);mc.lineTo(mag.width/2,mag.height);mc.moveTo(0,mag.height/2);mc.lineTo(mag.width,mag.height/2);mc.stroke();const m=paletteMatches[activeSampler];$('magnifierLabel').textContent=m?`${['Base','Secondary','Tertiary'][activeSampler]} · ${m.best.name} · RGB ${m.rgb.join(', ')}`:['Base','Secondary','Tertiary'][activeSampler]}

$('furFile').onchange=e=>{const file=e.target.files?.[0];if(!file)return;const u=window.URL.createObjectURL(file),im=new Image();im.onload=()=>{furImage=im;fCanvas.width=im.naturalWidth;fCanvas.height=im.naturalHeight;fctx.drawImage(im,0,0);window.URL.revokeObjectURL(u);$('furWorkspace').hidden=false;$('furStatus').textContent=`Loaded ${file.name}`;renderFur()};im.src=u};
document.querySelectorAll('.furSlot').forEach(b=>b.onclick=()=>{furActive=+b.dataset.slot;document.querySelectorAll('.furSlot').forEach(x=>x.classList.toggle('active',x===b))});
fCanvas.onclick=e=>{if(!furImage)return;const r=fCanvas.getBoundingClientRect(),x=(e.clientX-r.left)*fCanvas.width/r.width,y=(e.clientY-r.top)*fCanvas.height/r.height;furSamples[furActive].push(samplePatch(fctx,fCanvas,x,y,5));renderFur()};
$('furUndo').onclick=()=>{furSamples[furActive].pop();renderFur()};
$('furClear').onclick=()=>{furSamples[furActive]=[];renderFur()};
function renderFur(){const names=['Primary','Secondary','Tertiary'];$('furResults').innerHTML=furSamples.map((arr,i)=>{if(!arr.length)return`<article class="result"><h3>${names[i]}</h3><div class="muted">No points sampled</div></article>`;const rgb=[0,1,2].map(c=>median(arr.map(x=>x[c]))),best=rankRgb(rgb)[0];return`<article class="result"><h3>${names[i]}</h3><div class="colourRow"><span class="swatch" style="background:${best.hex}"></span>${best.name}</div><div class="code">${arr.length} fur points · estimated</div></article>`}).join('')}

async function runOcr(){const badge=$('ocrBadge');if(!window.Tesseract){badge.textContent='Enter details manually';return}try{badge.textContent='Reading name and pattern…';const nr=await Tesseract.recognize(crop(pCanvas,.04,.12,.25,.23),'eng',{tessedit_pageseg_mode:7}),pr=await Tesseract.recognize(crop(pCanvas,.04,.30,.25,.39),'eng',{tessedit_pageseg_mode:7});const n=(nr.data.text||'').toUpperCase().replace(/[^A-Z0-9 _-]/g,' ').replace(/\s+/g,' ').trim();if(n)$('kubrowName').value=n;const t=(pr.data.text||'').replace(/fur\s*pattern/ig,'').replace(/[^a-z -]/ig,' ').replace(/\s+/g,' ').trim(),known=['Lotus','Merle','Patchy','Striped','Hound'],k=known.find(x=>t.toLowerCase().includes(x.toLowerCase()));if(k)$('pattern').value=k;else if(t.length>2)$('pattern').value=t.replace(/\b\w/g,c=>c.toUpperCase());badge.textContent='OCR complete — please check'}catch(e){badge.textContent='Enter details manually'}}

function initSupabase(){if(!window.supabase)return;sb=window.supabase.createClient('https://mxboguiriifkmsmcusjt.supabase.co','sb_publishable_gZwUnRiKV2Ww2wqAXs9mBA_Z8lFw0LV');sb.auth.onAuthStateChange((_e,s)=>{session=s;auth()});sb.auth.getSession().then(x=>{session=x.data.session;auth()})}function auth(){$('signedOut').hidden=!!session;$('signedIn').hidden=!session;if(session)$('accountEmail').textContent=session.user.email||'breeder'}
$('signIn').onclick=async()=>{if(!sb)return saveMsg('Sign-in service unavailable.');const{error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});saveMsg(error?error.message:'Signed in.')};$('signOut').onclick=()=>sb&&sb.auth.signOut();
$('saveKennel').onclick=async()=>{if(!sb||!session)return saveMsg('Sign in first.');if(!paletteFile||paletteMatches.length!==3)return saveMsg('Upload and place all samplers first.');if(paletteMatches.some(m=>m.mixed||m.best.d>12))return saveMsg('At least one sampler is not clean enough to save as Palette Verified.');const name=$('kubrowName').value.trim(),breed=$('breed').value,pattern=$('pattern').value.trim();if(!name||!breed||!pattern)return saveMsg('Check name, breed and pattern.');if(!$('detailsConfirmed').checked)return saveMsg('Tick the confirmation box.');const duplicate=await sb.from('kennel_kubrows').select('id,name').eq('owner_id',session.user.id).eq('name',name).maybeSingle();if(duplicate.data&&!confirm(`A Kubrow named ${name} already exists. Save another record?`))return;saveMsg('Uploading screenshot…');const ext=(paletteFile.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,''),path=`${session.user.id}/${crypto.randomUUID()}.${ext}`,up=await sb.storage.from('kennel-screenshots').upload(path,paletteFile,{contentType:paletteFile.type||'image/jpeg'});if(up.error)return saveMsg(up.error.message);const payload={owner_id:session.user.id,name,breed,pattern,build_type:$('buildType').value||null,gender:$('gender').value||null,primary_colour:paletteMatches[0].best.name,secondary_colour:paletteMatches[1].best.name,tertiary_colour:paletteMatches[2].best.name,eye_colour:$('eyes').value||null,verification_source:'screenshot',imprints_remaining:$('imprints').value===''?null:+$('imprints').value,trade_status:$('tradeStatus').value,asking_price:$('askingPrice').value===''?null:+$('askingPrice').value,notes:$('notes').value.trim()||null,screenshot_path:path,is_public:false};const{error}=await sb.from('kennel_kubrows').insert(payload);if(error){await sb.storage.from('kennel-screenshots').remove([path]);return saveMsg(error.message)}saveMsg('Saved to My Kennel as Palette Verified.')};
function saveMsg(t){$('saveStatus').textContent=t}

function loadLayout(){try{return JSON.parse(localStorage.getItem('ljwillylPaletteLayout'))}catch{return null}}
function rankPatch(c,can,p,r){const x=p.x*can.width,y=p.y*can.height,rgb=samplePatch(c,can,x,y,r),variance=patchVar(c,can,x,y,r),rank=rankRgb(rgb);return{rgb,best:rank[0],mixed:variance>14}}
function rankRgb(rgb){const lab=toLab(rgb);return PALETTE.map(c=>({...c,d:de(lab,c.lab)})).sort((a,b)=>a.d-b.d)}
function samplePatch(c,can,cx,cy,r){const x=Math.max(0,Math.round(cx-r)),y=Math.max(0,Math.round(cy-r)),w=Math.min(can.width-x,r*2+1),h=Math.min(can.height-y,r*2+1),d=c.getImageData(x,y,w,h).data,a=[[],[],[]];for(let i=0;i<d.length;i+=4){const mx=Math.max(d[i],d[i+1],d[i+2]),mn=Math.min(d[i],d[i+1],d[i+2]);if(mx>240&&mx-mn<25)continue;a[0].push(d[i]);a[1].push(d[i+1]);a[2].push(d[i+2])}return a.map(v=>median(v))}
function patchVar(c,can,cx,cy,r){const x=Math.max(0,Math.round(cx-r)),y=Math.max(0,Math.round(cy-r)),w=Math.min(can.width-x,r*2+1),h=Math.min(can.height-y,r*2+1),d=c.getImageData(x,y,w,h).data,v=[];for(let i=0;i<d.length;i+=4)v.push((d[i]+d[i+1]+d[i+2])/3);const m=v.reduce((a,b)=>a+b,0)/(v.length||1);return Math.sqrt(v.reduce((a,b)=>a+(b-m)**2,0)/(v.length||1))}
function median(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y);return b[Math.floor(b.length/2)]}function h2r(h){return[1,3,5].map(i=>parseInt(h.slice(i,i+2),16))}function lin(v){v/=255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4)}function toLab(c){let[r,g,b]=c.map(lin),x=(.4124*r+.3576*g+.1805*b)/.95047,y=.2126*r+.7152*g+.0722*b,z=(.0193*r+.1192*g+.9505*b)/1.08883,f=t=>t>.008856?Math.cbrt(t):7.787*t+16/116;return[116*f(y)-16,500*(f(x)-f(y)),200*(f(y)-f(z))]}function de(a,b){return Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2])}function clamp(v){return Math.max(0,Math.min(1,v))}function crop(can,x1,y1,x2,y2){const c=document.createElement('canvas'),sx=x1*can.width,sy=y1*can.height,sw=(x2-x1)*can.width,sh=(y2-y1)*can.height;c.width=sw*3;c.height=sh*3;c.getContext('2d').drawImage(can,sx,sy,sw,sh,0,0,c.width,c.height);return c}
initSupabase();
});