"use strict";const sb=window.KubrowApp.getSupabaseClient(),$=id=>document.getElementById(id);let rows=[],session=null,wishes=[];const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function load(){session=(await sb.auth.getSession()).data.session;const pub=await sb.from("public_kubrow_dna_complete").select("*").order("name");rows=pub.data||[];if(session){const mine=await sb.from("kennel_kubrows").select("*").eq("owner_id",session.user.id).order("name");(mine.data||[]).forEach(r=>{if(!rows.some(x=>x.id===r.id))rows.push({...r,owner_name:"My Kennel"})});$("authState").textContent="Your private kennel and approved public DNA records are available.";await loadWishes()}fill()}
function fill(){const opts=rows.map(r=>`<option value="${r.id}">${esc(r.name)} · ${esc(r.kdna_id||"private")} · ${esc(r.owner_name||"Public")}</option>`).join("");$("parentA").innerHTML='<option value="">Choose parent A</option>'+opts;$("parentB").innerHTML='<option value="">Choose parent B</option>'+opts}
function val(r,k){return r?.[k]||"Unknown"}function compare(){const a=rows.find(r=>String(r.id)===$("parentA").value),b=rows.find(r=>String(r.id)===$("parentB").value);if(!a||!b){$("comparison").innerHTML='<p class="warn">Choose two parents.</p>';return}const traits=[["Breed","breed"],["Pattern","pattern"],["Build","build_type"],["Primary","primary_colour"],["Secondary","secondary_colour"],["Tertiary","tertiary_colour"],["Eyes","eye_colour"],["Gender","gender"]];$("comparison").innerHTML=`<div class="grid cards" style="margin-top:15px">${traits.map(([n,k])=>`<article class="card"><div class="body"><div class="eyebrow">${n}</div><h3>${esc(val(a,k))} <span class="muted">or</span> ${esc(val(b,k))}</h3><p class="meta">${val(a,k)===val(b,k)?"Both parents match this trait.":"The offspring may inherit either parent's recorded trait."}</p></div></article>`).join("")}</div><div class="panel warn"><b>Planning note:</b> this comparison lists parent traits and matching traits. It is not a guaranteed prediction or percentage calculator.</div>`}
$("compare").onclick=compare;$("swap").onclick=()=>{const a=$("parentA").value;$("parentA").value=$("parentB").value;$("parentB").value=a;compare()};
function wishPayload(){return{name:$("wishName").value.trim()||"Dream Kubrow",breed:$("wishBreed").value.trim()||null,pattern:$("wishPattern").value.trim()||null,build_type:$("wishBuild").value||null,primary_colour:$("wishPrimary").value.trim()||null,secondary_colour:$("wishSecondary").value.trim()||null,tertiary_colour:$("wishTertiary").value.trim()||null}}
$("saveWish").onclick=async()=>{if(!session){$("wishMessage").textContent="Sign in through My Kennel before saving a wishlist.";return}const p={...wishPayload(),owner_id:session.user.id};const{error}=await sb.from("kubrow_wishlists").insert(p);$("wishMessage").textContent=error?error.message:"Wishlist saved.";if(!error)loadWishes();match(p)}
async function loadWishes(){const{data}=await sb.from("kubrow_wishlists").select("*").eq("owner_id",session.user.id).order("created_at",{ascending:false});wishes=data||[];$("savedWishes").innerHTML=wishes.map(w=>`<div class="panel"><b>${esc(w.name)}</b><span class="meta"> · ${esc([w.breed,w.pattern,w.build_type,w.primary_colour,w.secondary_colour,w.tertiary_colour].filter(Boolean).join(" · "))}</span><div class="actions"><button class="ghost" data-match="${w.id}">Find matches</button><button class="danger" data-del="${w.id}">Delete</button></div></div>`).join("");document.querySelectorAll("[data-match]").forEach(b=>b.onclick=()=>match(wishes.find(w=>w.id===b.dataset.match)));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{await sb.from("kubrow_wishlists").delete().eq("id",b.dataset.del).eq("owner_id",session.user.id);loadWishes()})}
function match(w){const keys=["breed","pattern","build_type","primary_colour","secondary_colour","tertiary_colour"],active=keys.filter(k=>w[k]);const scored=rows.map(r=>({...r,score:active.filter(k=>(r[k]||"").toLowerCase()===String(w[k]).toLowerCase()).length,total:active.length})).filter(r=>r.total&&r.score).sort((a,b)=>b.score-a.score).slice(0,12);$("matches").innerHTML=scored.map(r=>`<article class="card"><div class="body"><span class="pill kdna">${esc(r.kdna_id||"PRIVATE")}</span><h3>${esc(r.name)}</h3><div class="meta">${r.score}/${r.total} target traits matched</div>${r.kdna_id?`<a class="button ghost" style="margin-top:10px" href="dna.html?id=${encodeURIComponent(r.kdna_id)}">View DNA</a>`:""}</div></article>`).join("")||'<p class="muted">No current public or kennel records match the target.</p>'}
load();